aplication/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  resources :fuselages
  resources :gears
  resources :tails
  resources :wings
  resources :cabins
  resources :engines
  resources :categories
  resources :planes
  root "public#index.html"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

aplication/app/models/gear.rb
class Gear < ApplicationRecord
	has_many :planes
end

aplication/app/controllers/gears_controller.rb
class GearsController < ApplicationController
  before_action :set_gear, only: [:show, :edit, :update, :destroy]

  # GET /gears
  # GET /gears.json
  def index
    @gears = Gear.all
  end

  # GET /gears/1
  # GET /gears/1.json
  def show
  end

  # GET /gears/new
  def new
    @gear = Gear.new
  end

  # GET /gears/1/edit
  def edit
  end

  # POST /gears
  # POST /gears.json
  def create
    @gear = Gear.new(gear_params)

    respond_to do |format|
      if @gear.save
        format.html { redirect_to @gear, notice: 'Gear was successfully created.' }
        format.json { render :show, status: :created, location: @gear }
      else
        format.html { render :new }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gears/1
  # PATCH/PUT /gears/1.json
  def update
    respond_to do |format|
      if @gear.update(gear_params)
        format.html { redirect_to @gear, notice: 'Gear was successfully updated.' }
        format.json { render :show, status: :ok, location: @gear }
      else
        format.html { render :edit }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gears/1
  # DELETE /gears/1.json
  def destroy
    @gear.destroy
    respond_to do |format|
      format.html { redirect_to gears_url, notice: 'Gear was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gear
      @gear = Gear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gear_params
      params.require(:gear).permit(:name, :description)
    end
end

aplication/app/helpers/gears_helper.rb
module GearsHelper
end

aplication/app/views/gears/_form.html.erb
<%= form_for(gear) do |f| %>
  <% if gear.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gear.errors.count, "error") %> prohibited this gear from being saved:</h2>

      <ul>
      <% gear.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

aplication/app/views/gears/edit.html.erb
<h1>Editing Gear</h1>

<%= render 'form', gear: @gear %>

<%= link_to 'Show', @gear %> |
<%= link_to 'Back', gears_path %>

aplication/app/views/gears/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gears</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gears.each do |gear| %>
      <tr>
        <td><%= gear.name %></td>
        <td><%= gear.description %></td>
        <td><%= link_to 'Show', gear %></td>
        <td><%= link_to 'Edit', edit_gear_path(gear) %></td>
        <td><%= link_to 'Destroy', gear, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gear', new_gear_path %>

aplication/app/views/gears/new.html.erb
<h1>New Gear</h1>

<%= render 'form', gear: @gear %>

<%= link_to 'Back', gears_path %>

aplication/app/views/gears/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gear.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gear.description %>
</p>

<%= link_to 'Edit', edit_gear_path(@gear) %> |
<%= link_to 'Back', gears_path %>