aplication/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  resources :fuselages
  resources :gears
  resources :tails
  resources :wings
  resources :cabins
  resources :engines
  resources :categories
  resources :planes
  root "public#index.html"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

aplication/app/models/fuselage.rb
class Fuselage < ApplicationRecord
	has_many :planes
end

aplication/app/controllers/fuselages_controller.rb
class FuselagesController < ApplicationController
  before_action :set_fuselage, only: [:show, :edit, :update, :destroy]

  # GET /fuselages
  # GET /fuselages.json
  def index
    @fuselages = Fuselage.all
  end

  # GET /fuselages/1
  # GET /fuselages/1.json
  def show
  end

  # GET /fuselages/new
  def new
    @fuselage = Fuselage.new
  end

  # GET /fuselages/1/edit
  def edit
  end

  # POST /fuselages
  # POST /fuselages.json
  def create
    @fuselage = Fuselage.new(fuselage_params)

    respond_to do |format|
      if @fuselage.save
        format.html { redirect_to @fuselage, notice: 'Fuselage was successfully created.' }
        format.json { render :show, status: :created, location: @fuselage }
      else
        format.html { render :new }
        format.json { render json: @fuselage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fuselages/1
  # PATCH/PUT /fuselages/1.json
  def update
    respond_to do |format|
      if @fuselage.update(fuselage_params)
        format.html { redirect_to @fuselage, notice: 'Fuselage was successfully updated.' }
        format.json { render :show, status: :ok, location: @fuselage }
      else
        format.html { render :edit }
        format.json { render json: @fuselage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fuselages/1
  # DELETE /fuselages/1.json
  def destroy
    @fuselage.destroy
    respond_to do |format|
      format.html { redirect_to fuselages_url, notice: 'Fuselage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fuselage
      @fuselage = Fuselage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fuselage_params
      params.require(:fuselage).permit(:name, :description)
    end
end

aplication/app/helpers/fuselages_helper.rb
module FuselagesHelper
end

aplication/app/views/fuselages/_form.html.erb
<%= form_for(fuselage) do |f| %>
  <% if fuselage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fuselage.errors.count, "error") %> prohibited this fuselage from being saved:</h2>

      <ul>
      <% fuselage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

aplication/app/views/fuselages/edit.html.erb
<h1>Editing Fuselage</h1>

<%= render 'form', fuselage: @fuselage %>

<%= link_to 'Show', @fuselage %> |
<%= link_to 'Back', fuselages_path %>

aplication/app/views/fuselages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fuselages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fuselages.each do |fuselage| %>
      <tr>
        <td><%= fuselage.name %></td>
        <td><%= fuselage.description %></td>
        <td><%= link_to 'Show', fuselage %></td>
        <td><%= link_to 'Edit', edit_fuselage_path(fuselage) %></td>
        <td><%= link_to 'Destroy', fuselage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fuselage', new_fuselage_path %>

aplication/app/views/fuselages/new.html.erb
<h1>New Fuselage</h1>

<%= render 'form', fuselage: @fuselage %>

<%= link_to 'Back', fuselages_path %>

aplication/app/views/fuselages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fuselage.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fuselage.description %>
</p>

<%= link_to 'Edit', edit_fuselage_path(@fuselage) %> |
<%= link_to 'Back', fuselages_path %>