aplication/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  resources :fuselages
  resources :gears
  resources :tails
  resources :wings
  resources :cabins
  resources :engines
  resources :categories
  resources :planes
  root "public#index.html"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

aplication/app/models/tail.rb
class Tail < ApplicationRecord
	has_many :planes
end

aplication/app/controllers/tails_controller.rb
class TailsController < ApplicationController
  before_action :set_tail, only: [:show, :edit, :update, :destroy]

  # GET /tails
  # GET /tails.json
  def index
    @tails = Tail.all
  end

  # GET /tails/1
  # GET /tails/1.json
  def show
  end

  # GET /tails/new
  def new
    @tail = Tail.new
  end

  # GET /tails/1/edit
  def edit
  end

  # POST /tails
  # POST /tails.json
  def create
    @tail = Tail.new(tail_params)

    respond_to do |format|
      if @tail.save
        format.html { redirect_to @tail, notice: 'Tail was successfully created.' }
        format.json { render :show, status: :created, location: @tail }
      else
        format.html { render :new }
        format.json { render json: @tail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tails/1
  # PATCH/PUT /tails/1.json
  def update
    respond_to do |format|
      if @tail.update(tail_params)
        format.html { redirect_to @tail, notice: 'Tail was successfully updated.' }
        format.json { render :show, status: :ok, location: @tail }
      else
        format.html { render :edit }
        format.json { render json: @tail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tails/1
  # DELETE /tails/1.json
  def destroy
    @tail.destroy
    respond_to do |format|
      format.html { redirect_to tails_url, notice: 'Tail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tail
      @tail = Tail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tail_params
      params.require(:tail).permit(:name, :description)
    end
end

aplication/app/helpers/tails_helper.rb
module TailsHelper
end

aplication/app/views/tails/_form.html.erb
<%= form_for(tail) do |f| %>
  <% if tail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tail.errors.count, "error") %> prohibited this tail from being saved:</h2>

      <ul>
      <% tail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

aplication/app/views/tails/edit.html.erb
<h1>Editing Tail</h1>

<%= render 'form', tail: @tail %>

<%= link_to 'Show', @tail %> |
<%= link_to 'Back', tails_path %>

aplication/app/views/tails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tails.each do |tail| %>
      <tr>
        <td><%= tail.name %></td>
        <td><%= tail.description %></td>
        <td><%= link_to 'Show', tail %></td>
        <td><%= link_to 'Edit', edit_tail_path(tail) %></td>
        <td><%= link_to 'Destroy', tail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tail', new_tail_path %>

aplication/app/views/tails/new.html.erb
<h1>New Tail</h1>

<%= render 'form', tail: @tail %>

<%= link_to 'Back', tails_path %>

aplication/app/views/tails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tail.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tail.description %>
</p>

<%= link_to 'Edit', edit_tail_path(@tail) %> |
<%= link_to 'Back', tails_path %>